services:
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 128m
    env_file:
      - ./.env
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
